#!/bin/sh

if [ "$(makoctl mode)" = "default" ]; then
  class="off"
  if [ "$1" = "toggle" ]; then
    makoctl mode -s dnd
    class="on"
  fi
elif [ "$(makoctl mode)" = "dnd" ]; then
  class="on"
  if [ "$1" = "toggle" ]; then
    makoctl mode -s default
    class="off"
  fi
fi

printf '{"alt":"%s"}\n' "$class"
#echo "{\"alt\": \"${status}\"}"
